### ISSUE TITLE
Logitech reliability

### ISSUE THREAD

**Issue by RetoSchaedler** [insecurityofthings/jackit#14]
Hi. The Injection works now perfect for Microsoft products. But with Logitech products, an injection of 3k keys does miss a few characters (on random positions). Is it possible to improve the code for Logitech products? Thanks R8o

**Comment by infamy** [comment]
I have noticed the same thing. And have been working on trying to turn the Logitech injection a bit better.

You can play with the delay between keystrokes. We will try and make more improvements over the next few weeks.

**Comment by SteckA** [comment]
Could there be an issue of when the dongle switches channels mid script? My scripts (fairly short) will just stop at random points in the script.

**Comment by infamy** [comment]
Should be improved as of the last commit. Please report back if you still have issues.
