### ISSUE TITLE
Support for the Logitech Unifying dongle

### ISSUE THREAD

**Issue by swherdman** [insecurityofthings/jackit#16]
Support for the Logitech Unifying dongle as per https://github.com/BastilleResearch/mousejack#flash-a-logitech-unifying-dongle

**Comment by swherdman** [comment]
Confirme working, Think it just needs a text update to indicate this dongle works

**Comment by infamy** [comment]
Yeah some updates to the script wording, is needed. But for attacking a unifying dongle is sort of useless. The range is TERRIBLE compared to the crazy radio. So doubt I will update the wording.
