### ISSUE TITLE
Logitech M510 with Unifiying adapter not working

### ISSUE THREAD

**Issue by c0d3z3r0** [insecurityofthings/jackit#17]
I tried jackit with a flashed Unifying adapter and with an selfmade USB-AVR-NRF24L01+ adapter.
In both cases I cannot inject keystrokes. Ping and sending packets works but the target Linux-PC doesn't receive any keystrokes.

Logitech M510 firmware 062.000.00013
Adapter C-U0008 version RQR24.01_B0023 / 024.001.00023

**Comment by infamy** [comment]
Attacking a unifying dongle on Linux will not work. You need to have a NON
linux target machine. This is because the linux driver will not accept
keystrokes in mouse packets. So attacking logitech, only works if the host
is osx, or windows.

**Comment by WiredLife** [comment]
This is not correct. I successfully injected keystrokes in a unifying dongle of k400r keyboard which was plugged in a ubuntu 14.04 machine (kodibuntu).

**Comment by phikshun** [comment]
That might be the case. Linux seems smart enough to filter keyboard HID values when it knows the device is a mouse, but it might allow keyboard HID codes when a combo device is in use.
