### ISSUE TITLE
injection only works good first time after wakeup

### ISSUE THREAD

**Issue by WiredLife** [insecurityofthings/jackit#19]
Hello :)
I have Kali 2016.2 on my netbook and when i wakeup from standby and run a injection it works most of the time.
But after the first injection i get nearly everytime a ping failed :(
Then i close the netbook, wait some seconds and open it again, login and run injection again, then it works like before.
Any idea?
Maybe there is something in the ram which is cleaned when it goes to standby?
Unplug and replugging the crazy stick does not solve the problem. Only a "go to standby and wakeup again".

I tested with Logitech K400r and MK260, both worked first time perfect and then only after the standby method.

Edit:
Ok forget that.
When i constantly move the mouse on the target, every injection fully works.
When i dont move the move the mouse constantly only the first part of the ducky script is transmitted or nothing.
Maybe its a timeout of the connection or something like that.

**Comment by phikshun** [comment]
We're missing Logitech keepalive support in the code. It's a fairly simple fix, we just need to send an extra frame to wake up the adapter. It will also prevent the dongle from changing channels during an injection attempt. I'll try to add the feature later this week.

**Comment by phikshun** [comment]
I added the code for the hello and keepalive mechanism. Should be more reliable when there's no downstream device to keep the receiver awake.

**Comment by WiredLife** [comment]
Is this code already included in uC Mousejack?

**Comment by phikshun** [comment]
In the latest commit, yes. I couldn't exactly replicate the issue on my hardware, but it seemed to help when I didn't have a downstream device sending keepalives. However, the channel detection ping was a little unreliable. Does it work for you?
