### ISSUE TITLE
Cannot send a simple 'SHIFT' keypress

### ISSUE THREAD

**Issue by nizedk** [insecurityofthings/jackit#20]
I'd really like to simply send the key-down key-up of the shift key once, however, no matter what I try, the pydecoder will not accept it

if I try

GUI

or

SHIFT

or

CTRL

nothing happens, but if I pair them with a key, it works. unfortunately, SHIFT CTRL fails the same way.

Could you add funtionality so that you could press/depress GUI, CTRL, SHIFT etc. ?

Br,
Martin

**Comment by phikshun** [comment]
Works in new build.
