### ISSUE TITLE
")" won't inject when place after "0"

### ISSUE THREAD

**Issue by this-post** [insecurityofthings/jackit#22]
Hi, thank you for your fantastic script

I've some problem regarding on title.
For example ,when write a string "(8080)" into duck script and inject keystroke to vulnerable mouse, the string will be "(808)" which is unexpected result (my workaround solution is store set of problem string into variable)

**Comment by phikshun** [comment]
Yeah, sorry about that. Fixed in the latest commit. This was due to some optimizations I created, but obviously didn't test very well.
