### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by ankushgoel27** [insecurityofthings/jackit#24]
Hi,

Can you also include other Mouse Types here. Currently it only covers logitech and microsoft. Dell would be  a nice one to have.

**Comment by phikshun** [comment]
Sorry, we haven't had time to work on other devices. It's not hard to do, it's just a hassle to order a truckload of vulnerable devices from eBay.

If you really want to add a device, I recommend reading Bastille's Defcon paper on the vulnerability. You can find it at https://github.com/BastilleResearch/mousejack/tree/master/doc/pdf. If you get it working, please send a pull request :)

**Comment by infamy** [comment]
We have started to add more devices. Amazon Basic has been added. More to come. We are willing to take hardware donations... *hint hint*

**Comment by ankushgoel27** [comment]
Lol, I am happy to donate money. What is your donation link?
