### ISSUE TITLE
RF Address and Physical Device

### ISSUE THREAD

**Issue by mkannan22** [insecurityofthings/jackit#26]
Is there a way to identify devices beforehand, such as in Device Manager on Windows and tie it back to the Address column listed under jackit script so one would know which device they are "attacking"?

**Comment by infamy** [comment]
You would need the Device ID of the dongle, which is tricky to get. I believe the Logitech Unified Dongle tool can do that. (Never used it...)

**Comment by mkannan22** [comment]
Thanks. Gave that a shot and it returned lots of info, just not exactly connecting back to what I see under the Address column in jackit. Unfortunately, Device ID is not part of the information from this tool. I will keep searching for other tools to connect the RF Address under the jackit tool to what is actually installed on a Windows computer to ultimately build an inventory of what is currently owned by us to ensure we are only "attacking" known devices.

**Comment by mkannan22** [comment]
Actually found almost exactly what I am looking for with that tool under the Serial Number. Thanks!
