### ISSUE TITLE
Logitech G700s

### ISSUE THREAD

**Issue by green567** [insecurityofthings/jackit#27]
Could someone please clarify what's up with the G700s? It is listed as tested device in the readme. Was it tested positive or negative? Afaik there is no firmware update for the G700's dongle as there is for the other affected Logitech mice, right? It is not using the universal receiver.

**Comment by infamy** [comment]
I have a 700s it can be attacked. The fix would work on a universal dongle, I have not tried patching the dongle form mine. (As I use it to test the tool)
