### ISSUE TITLE
python setup.py

### ISSUE THREAD

**Issue by backter** [insecurityofthings/jackit#30]
[
![setup](https://user-images.githubusercontent.com/29911117/28148183-b5451f60-67b7-11e7-8f4c-b8fe1eaf912c.JPG)
](url)

how to solve?

**Comment by infamy** [comment]
What version of Setup tools are you using.

**Comment by backter** [comment]
i don't how to see  version of Setup tools   (command)

**Comment by infamy** [comment]
Try again should be resolved.., closing for now

**Comment by needUpgrades** [comment]
Didn't work for me either so tried using "python setup.py install" and it gave errors , "using pip install ." did the trick
